[package]
name = "FFT"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "DFT"
path = "src/DFT.rs"

[[bin]]
name = "FFT"
path = "src/FFT.rs"

[[bin]]
name = "TEST"
path = "src/image_test.rs"

[dependencies]
image = "0.25.9"
